# Generated by Django 2.2.7 on 2019-12-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='profile_images/'),
        ),
    ]
