# Generated by Django 2.2.7 on 2019-12-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileimage',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
