# Generated by Django 2.2.7 on 2020-01-25 06:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191212_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='createdOn',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserProfileImage',
        ),
    ]
