# Generated by Django 2.2.7 on 2020-01-27 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20200125_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('area', models.CharField(max_length=40)),
                ('rent', models.IntegerField()),
                ('numBedroom', models.IntegerField()),
                ('numBathroom', models.IntegerField()),
                ('numFloor', models.IntegerField()),
                ('imageReference', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
